// OAuth scope metadata shared between client (Svelte pages) and server. Must
// live in $lib (not $lib/server) so Svelte pages can import it.
import type { Scope } from './server/oauth';

export const SCOPE_DESCRIPTIONS: Record<Scope, string> = {
	'trips:read': 'View trips and itinerary',
	'trips:write': 'Create, update, delete, and archive trips',
	'segments:read': 'View trip segments (flights, hotels, events)',
	'segments:write': 'Create, update, delete, and reschedule segments',
	'packing:read': 'View packing checklists and templates',
	'packing:write': 'Manage packing checklists and template items',
	'budgets:read': 'View trip budgets and spending',
	'budgets:write': 'Set or update trip budget categories',
	'expenses:read': 'View trip expenses and receipts',
	'expenses:write': 'Create, update, and delete trip expenses',
	'places:read': 'View visited countries and U.S. states',
	'places:write': 'Mark or unmark visited countries and U.S. states',
	'reminders:read': 'View your reminders',
	'reminders:write': 'Create, update, and delete your reminders',
	'profile:read': 'Read travel documents and pre-canned summaries',
	'companions:read': 'View trip companions',
	'companions:write': 'Add, update, or remove trip companions',
	'sharing:read': 'View trip shares and groups',
	'sharing:write': 'Create, update, or revoke trip shares and groups',
	'calendar:read': 'View calendar feed URLs and tokens',
	'calendar:write': 'Rotate or revoke calendar feed tokens',
	'templates:read': 'View trip and packing templates',
	'templates:write': 'Create or delete trip and packing templates',
	'travel-docs:read': 'View travel documents (passport, visa, etc.)',
	'travel-docs:write': 'Create, update, and delete travel documents',
	'doc-links:read': 'View per-trip document links',
	'doc-links:write': 'Create, update, and delete per-trip document links',
	'fares:read': 'View fare watches and prices',
	'fares:write': 'Create, update, and delete fare watches',
	'polls:read': 'View trip decision polls',
	'polls:write': 'Create polls and cast votes',
	'journal:read': 'View trip journal entries',
	'journal:write': 'Create, update, and delete trip journal entries',
	'items:read': 'View important items (valuables, trackers)',
	'items:write': 'Create, update, and delete important items',
	'requirements:read': 'View entry requirements (visa, vaccination)',
	'requirements:write': 'Create, update, and delete entry requirements',
	'home-tasks:read': 'View pre-departure to-dos',
	'home-tasks:write': 'Create, toggle, and delete home tasks',
	'medications:read': 'View trip medications',
	'medications:write': 'Create, update, and delete trip medications',
	'cards:read': 'View payment cards and benefits (no full PAN)',
	'cards:write': 'Create, update, and delete payment cards',
	'loyalty:read': 'View loyalty programs (no member numbers by default)',
	'loyalty:write': 'Create, update, and delete loyalty programs',
	'insurance:read': 'View insurance policies (no policy numbers by default)',
	'insurance:write': 'Create, update, and delete insurance policies',
	'contacts:read': 'View emergency contacts',
	'contacts:write': 'Create, update, and delete emergency contacts',
	'profile-prefs:read': 'View profile preferences (timezone, leads, currency)',
	'profile-prefs:write': 'Update profile preferences',
	'notifications:read': 'View per-channel notification toggles',
	'notifications:write': 'Update per-channel notification toggles',
	'user-smtp:read': 'View your SMTP override (password read is admin-only)',
	'user-smtp:write': 'Set or clear your SMTP override',
	'comments:read': 'View trip comments',
	'comments:write': 'Create and delete your trip comments',
	'search:read': 'Run global search across your account',
	'admin:read': 'View users, audit events, and system statistics (admins only)',
	'admin:write': 'Create, update, delete, and reset users (admins only)',
	'security:read': 'View your security settings, sessions, passkeys, and OAuth clients',
	'security:write': 'Change security settings and revoke your sessions or credentials'
};
